### ISSUE TITLE
Caso1: PruebasGancho - No hace falta poner el cursor encima del punto de enganche

### ISSUE THREAD

**Issue by jmeitin** [Proyectos1-FDI-UCM/c1920-Grupo06#1]
**Descripción**
Cuando lanzas el gancho a un pivote para salir propulsado, no es necesario poner el cursor sobre el pivote. Con que la recta formada por la posición del jugador y el cursor tambien corte con la posición del enganche, y este dentro de rango, el gancho se activa siempre.

**Pasos**
1.          Colocarse debajo de un pivote.
2.         Apretar el botón izquierdo.
3.         Colocar el cursor muy por encima/debajo del pivote
4.         Soltar el botón izquierdo.

**Captura de pantalla o vídeo**
https://drive.google.com/file/d/1vqu6SP33EU20fJi3RkElpOQPEQsRI2m2/view?usp=sharing

**Comment by aarmor01** [comment]
La mecánica del gancho está pensada de esa manera, el puntero te permite apuntar en la dirección que se desea, pero el gancho parará o bien al llevar a un punto de enganche, o bien por alcanzar el máximo de rango
