### ISSUE TITLE
Animacion de Dash estancada 

### ISSUE THREAD

**Issue by JosedaMachine** [Proyectos1-FDI-UCM/c1920-Grupo06#10]
Al saltar y rapidamente realizar un Dash hacia abajo de manera vertical con respecto al jugador, se realiza el Dash pero la animacion se queda estancada durante un tiempo variable. Además, el jugador se mueve a una velocidad horizontal tambien variable, incluso sin estar colisionando con nada continua moviendose y no recibe ningun efecto por la gravedad.
Pasos:
1.	Posicionarse en el suelo o cualquier plataforma.
2.	Saltar hacia cualquier dirección.
3.	Rápidamente, a continuación, realizar un dash vertical hacia abajo alineándolo con la posición del jugador en X. 

Video:
https://drive.google.com/file/d/1GpVyTqEhcT6ZZs6RUlmsXa9L0SZ0niry/view

**Comment by aarmor01** [comment]
Esto solo ocurría en la plataforma Jumpthrough, y ya está solucionado
