### ISSUE TITLE
La patada voladora lateral contra la plataforma de checkpoint produce un deslizamiento inesperado.

### ISSUE THREAD

**Issue by IvanPradoEchegaray** [Proyectos1-FDI-UCM/c1920-Grupo06#14]
Descripción
Se espera que al efectuar una patada voladora lateral contra la plataforma de checkpoint, el
avatar se detenga al chocar contra ella. Sin embargo, se produce un desplazamiento
vertical, similar al caso anterior de patada hacia abajo tras saltar. Siendo este error más
común y fácil de reproducir ya que no requiere la rapidez del caso previo.
Pasos
• Posicionarse de manera que el avatar este alineado con la plataforma en el eje x
• Pulsar clic derecho apuntando hacia la plataforma.
Vídeo
https://www.youtube.com/watch?v=8jArU7rYV9A

**Comment by aarmor01** [comment]
Este error sigue ocurriendo (aunque ahora, en lugar de seguir hacia arriba, el jugador continua moviendose en la dirección durante 'x' tiempo), pero en la práctica nunca debería ocurrir, pues al ser estas plataformas un "checkpoint" (no todas), están colocadas de esta manera.

![Checkpoint](https://user-images.githubusercontent.com/62306290/84060957-59e03380-a9bd-11ea-991e-285064bc980e.PNG)

De tal manera que el error se "soluciona" de forma similar al problema de las plataformas movibles y la "deathzone"
