### ISSUE TITLE
 Patada voladora hacia el lado contrario de pared rompible, la rompe

### ISSUE THREAD

**Issue by IvanPradoEchegaray** [Proyectos1-FDI-UCM/c1920-Grupo06#16]
Descripción
Se espera que al efectuar una patada voladora en dirección contraria a una pared rompible
mientras estas enganchado en la misma, el avatar salga despedido y la pared siga en pie. Sin
embargo, la pared se rompe.
Pasos
• Saltar hacia una pared rompible
• Pulsar clic derecho en dirección contraria a la pared
Vídeo
https://youtu.be/La13jUEH4xE

**Comment by aarmor01** [comment]
Es la intención, ahora con los efectos de partículas si que parece que el dash hace daño a la pared.
