### ISSUE TITLE
La plataforma móvl puede matar al avatar.

### ISSUE THREAD

**Issue by IvanPradoEchegaray** [Proyectos1-FDI-UCM/c1920-Grupo06#17]
Descripción
La plataforma móvil puede presionar sobre el avatar metiéndole en el suelo, provocando
un game over si el borde inferior de la pantalla se encuentra muy cercano al suelo. Se trata
de algo que tener en cuenta a la hora de diseñar los niveles teniendo cuidado de no
posicionar las plataformas móviles muy cerca del suelo.
Pasos
• Posicionarse en el suelo en el punto más bajo de una plataforma móvil
• Esperar a que el avatar sea empujado por la plataforma
Vídeo
https://youtu.be/vEoeMm0fovg

**Comment by aarmor01** [comment]
Se han retocado posiciones en el Nivel 2 que podían llevar a este error.
