### ISSUE TITLE
Caso1: PruebasGancho - El sprite del gacho no está bien ajustado

### ISSUE THREAD

**Issue by jmeitin** [Proyectos1-FDI-UCM/c1920-Grupo06#2]
**Descripción**
Al utilizar el gancho sobre un pivote que está justo al límite de longitud el gancho no llega a tocar el pivote si no que se queda a una pequeña distancia. Aun así sale disparado, por lo que da la sensación de que se ha enganchado al aire y no al pivote. Me imagino que será que el boxCollider de ese tipo de pivote en específico no estará bien ajustado.

**Pasos**

1.         En la escena 2 de las pruebas del gancho, colocarse justo debajo del pivote de la derecha del todo.
2.          Apretar el botón izquierdo.
3.         Colocar el cursor sobre el pivote
4.         Soltar el botón izquierdo.

**Captura de pantalla o vídeo**
https://drive.google.com/file/d/1LBVAZdohVD1Oc1WrFxszgFDcKma8FcHj/view?usp=sharing

**Comment by aarmor01** [comment]
No nos parece algo grave, es efecto visual solo ocurre a veces, no es un error per se
