### ISSUE TITLE
Movimiento del jugador se queda estancado al lanzar el gancho

### ISSUE THREAD

**Issue by adriac02** [Proyectos1-FDI-UCM/c1920-Grupo06#23]
Descripción:
Al lanzar el gancho estando en el aire y teniendo pulsada una tecla de dirección esperaba que el jugador pudiera seguir cambiando su dirección durante la camara lenta, en cambio, aunque dejes de pulsar la tecla, se sigue moviendo en la misma dirección que al principio.

Pasos:
1. Saltar y mantener pulsada una de las teclas de dirección.
2. Lanzar el gancho mientras se está pulsando la tecla de dirección.
3. Dejar de pulsar la tecla o intentarlo con la otra, vemos que el jugador está estancado.

Captura:
https://youtu.be/S5Cz_glt7c0

**Comment by aarmor01** [comment]
La idea de la ralentizacion es facilitar el apuntado, pero no cambia la dirección en la que el jugador se mueve (faltó haberlo explicado, pero como no era nuestro principal objetivo, no lo especificamos)
