### ISSUE TITLE
Caso2: Pruebas de Colisiones - La plataforma móvil te tira si te subes a ella

### ISSUE THREAD

**Issue by jmeitin** [Proyectos1-FDI-UCM/c1920-Grupo06#3]
**Descripción**
La plataforma móvil morada que gira subiendo y bajando tiene un comportamiento extraño. Cuando saltas y te colocas sobre ella, esta te arrastra hacia un extremo y te tira. Para no caerte tienes que moverte en sentido contrario. Es como cuando te pones en el último escalón de una escalera mecánica. Si te quedas quieto te tropiezas así que tienes que andar en sentido contrario para seguir en la escalera.

**Pasos**

1.         Colócate al lado de una plataforma móvil.
2.      Cuando esté en su punto más bajo, salta encima de ella.

**Captura de pantalla o vídeo**
https://drive.google.com/file/d/10yJCFRu18KbWfn-vd2zehNCLvYiYm4dw/view?usp=sharing

**Comment by IvanPradoEchegaray** [comment]
Al parecer, presionar cualquier tecla estando sobre una plataforma móvil
produce este comportamiento. No pulsar ninguna tecla produce el comportamiento esperado.

https://youtu.be/XdWPGptXhMk
