### ISSUE TITLE
Caso2: Pruebas de Colisiones - El Dash hacia abajo si estás pegado no funciona

### ISSUE THREAD

**Issue by jmeitin** [Proyectos1-FDI-UCM/c1920-Grupo06#4]
**Descripción**
En la escena 5 del Caso 2 hay un problema con el Dash. Mientra que la plataforma temporal desaparece con el Dash tanto si le das por un lado como por el otro, estés pegado a ella o no. Sin embargo, si te colocas sobre la horizontal y presionas la tecla derecha hacia abajo, no pasa nada. Tienes que saltar hacia arriba, y una vez en el aire presionar dicha tecla.

**Pasos**

1.         Colócate sobre una plataforma temporal horizontal.
2.      Coloca el cursor debajo de dicha plataforma.
3.      Presiona el botón derecho.

**Captura de pantalla o vídeo**
https://drive.google.com/file/d/1sNDEjQ9i7Kqy8rET4THD0DsfgnhsCVPz/view?usp=sharing

**Comment by aarmor01** [comment]
El dash como tal no se puede hacer hacia abajo cuando estás sobre una plataforma, perdón por no especificarlo.
