### ISSUE TITLE
Prueba 3 Power Ups - Escudo

### ISSUE THREAD

**Issue by angelo066** [Proyectos1-FDI-UCM/c1920-Grupo06#8]
**Descripción**
Al recibir daño, recoger el power up del escudo y activarlo, la animación de invulnerable se corta y da paso a la animación idle/movimiento del jugador dependiendo de si este se mueve o no.
**Pasos**
1. Hazte daño con cualquiera de los dos objetos que hay en la sala
2. Recoge el power up del escudo
3. Activalo rapidamente

**Comment by aarmor01** [comment]
Esa es la idea, la animación de invulnerabilidad se desactiva cuando se activa el escudo, pues ambos implican que el jugador sea invulnerable.
